### ISSUE TITLE
Show code button is not working on the demo page

### ISSUE THREAD

**Issue by GCorbel** [quantosobra/ember-data-table-light#2]
I think there is a lack of documentation for the moment. It's normal for young addon but it can be useful to add more doc.

Anyway, do you plan to maintain actively this project? It's useful but the its tons of things to do. I may contribute but I've not the time right now.

**Comment by eduardoweiland** [comment]
Yes, we will maintain this addon! We know that the documentation it's not very good at the moment, but we will work to improve it as soon as possible.

**Comment by GCorbel** [comment]
Cool. I'm talking about you're project on the Ember Community slack right now. It seems the documentation is an important things to do to become popular.
