### ISSUE TITLE
Problems with css

### ISSUE THREAD

**Issue by GCorbel** [quantosobra/ember-data-table-light#5]
I have some problems with CSS. 

First of all, I have to copy/paste the CSS from the dummy app. The box to choose visible columns is not totally visible. In addition, I don't like the fact than the scrollbar is included in a div. I prefer to use normal table and I don't know how to do. An option can be useful.

I'm not good with CSS. I can't do it myself.

**Comment by eduardoweiland** [comment]
This addon uses Ember Light Table to create the table. That is how it works. About the scrollbars, maybe you can ask about this issue on [their issue tracker](https://github.com/offirgolan/ember-light-table/)
